[package]
name = "owlosui-win"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The shared application in a native Windows window, through lib/window."

[[bin]]
name = "owlosui-win"
path = "src/main.rs"

[dependencies]
owlosui-core = { path = "../../../../lib/core" }
owlosui-window = { path = "../../../../lib/window" }
